### ISSUE TITLE
resolve_pageid() is deprecated.

### ISSUE THREAD

**Issue by GormCh** [gturri/nspages#146] opened 2023-04-23 08:38 UTC
Hi.
I am building a wiki for our housing coop. It seem to work fine but when looking through the log there seems to be an issue.
Perhaps some of you guys knows the answer right away.

Regards
Erik L.

[resolve_pageid() is deprecated.txt](https://github.com/gturri/nspages/files/11303238/resolve_pageid.is.deprecated.txt)

**Comment by gturri** [comment] 2023-04-23 08:54
hi,

Thanks for this bug report.
This is a duplicate of #145 so I'll close it.

In a nutshell the status is:
- this warning is absolutely not an issue
- in practice it just means that nspages is using some functions which are deprecated on the latest versions of dokuwiki, but which still works as fine as before
- it would be pretty easy to remove this warning: the fix is already available as the pull request #144 
- However, as-is, it would break the compatibility with older versions of dokuwiki, so we don't merge it for now

(don't hesitate to comment on #145 if you want to add something)

**Closed by gturri** 2023-04-23 08:54 UTC
