### ISSUE TITLE
"nspages -usePictures" only supports JPEG and PNG

### ISSUE THREAD

**Issue by sludgeFudge** [gturri/nspages#162] opened 2024-04-22 17:34 UTC
Hi, fantastic piece of software.
As the title says, using `nspages -usePictures` only supports images that are JPEG or PNG.
I would like to use newer formats such as JXL, AVIF and WEBP since they save so much more space. These formats are supported by dokuwiki (after tinkering with the config) and they display on the page, so I'm a little confused as to why nspages doesn't support this.

**Comment by gturri** [comment] 2024-04-22 19:30
Thanks for this bug report.

I might need a bit more context. Could you please let me know:
* what nspages flag you are using
* what tinkering you've done on Dokuwiki config
* what you mean by "not supported"? If it makes sense, could you share a screenshot?
* I'm also interested in what you're seeing in the network panel of the developer tools of your browser. There should be queries to urls like `https://turri.fr/dw/lib/exe/fetch.php?w=350&h=220&tok=<zzz>&media=<your_picture.webp>`. What is the status of those queries? Are they successful?

Thanks

**Comment by sludgeFudge** [comment] 2024-04-23 07:35
Sorry about that, what I meant by "not supported" was that the images would not display.

This is the nspages flag for a page I'm using:
```
<nspages -h1 -exclude:start -subns -nopages -exclude -usePictures -textNs="Anime in this Decade">
```

By tinkering, I meant adding a `mime.local.conf` file and adding the following to let these file types be uploaded:
```
avif    image/avif
jxl     image/jxl
cbz     image/cbz
cb7     image/cb7
```

So, what I mean by not supported is that the images that are not PNG or JPEG do not display when using the `-usePictures` flag. Here's an example.
![nspages-usePictures](https://github.com/gturri/nspages/assets/34100920/5bef92fc-aefa-4eca-8a4d-3b395abafd43)


All the pages that have an image display use a JPEG image, while Konosuba uses a JPEG XL image. Ignore Z-Kai, it does not have an image.
The same thing happens for WEBP and AVIF.
As you can see, dokuwiki displays the image when viewing the page.
![konosuba-uses-jxl](https://github.com/gturri/nspages/assets/34100920/658683f9-e5d8-4dcf-8e57-e148c13bb400)

I'm locally hosting my dokuwiki so there are no such issues with failing to reach them, but here's a screenshot.
![network-panel](https://github.com/gturri/nspages/assets/34100920/f23ecd37-fbcf-4d0d-924b-62d3c1c86308)

**Comment by gturri** [comment] 2024-04-23 08:23
Thanks for this information.

I think it probably has to do with what dokuwiki considers to be the "first image" of a page. In the sense that what nspages does is just

```
$meta = p_get_metadata($pageId);
$picture = $meta['relation']['firstimage'];
```
(snippet from https://github.com/gturri/nspages/blob/master/printers/printerPictures.php#L49 )
so I guess Dokuwiki metadata doesn't return a "first image" for that page.

I'll try to have a closer look into it soon to try to understand if there can be a workaround or something to fix.

**Comment by sludgeFudge** [comment] 2024-04-23 10:44
Hmm, interesting. Thanks for looking into this.

**Comment by gturri** [comment] 2024-04-23 20:14
I made a test. I tried with 3 pages:
* one with a png
* one without images at all
* one with a jxl

with this setup, I observe the same behavior as you, in the sense that I see Dokuwiki logo for each pages except the one with the png (which is correctly displayed as expected).

now, when I look into the "meta" files for those pages (ie: when I look into the files `data/meta/<my-namespace>/<my-page>.meta`, what I observe is:

* the meta file for the page with the png contains `"firstimage";s:19:"playground:test.png"`, which is expected)
* for the page with no image, it does not contain any `firstimage` key, which makes sense
* for the page with the jxl, it contains `"firstimage";s:0:"";`, which is incorrect

This confirms the intuition that the issue is on Dokuwiki side (which fails to fill `firstimage` when we use an exotic format

As long as this meta "firstimage" key is not correctly filled by Dokuwiki, there is no chance that nspages can display it correctly (and also, I guess that nspages should work as expected as soon as Dokuwiki behavior is fixed).
So I suggest that you open a bug report on Dokuwiki bugtracker instead. And since there is nothing to do here, I'll close this bug report. (But feel free to re-open it if you disagree)

**Closed by gturri** 2024-04-23 20:14 UTC

**Comment by sludgeFudge** [comment] 2024-04-23 23:31
Ok, will update here when I get feedback from the dokuwiki team.

**Comment by sludgeFudge** [comment] 2024-04-24 15:55
I've asked the dokuwiki team and it's as simple as changing the lines in [dokuwiki/inc/parser/metadata.php](https://github.com/dokuwiki/dokuwiki/blob/31afae8a5238b24d15fc0e6f342ee8341d1014dd/inc/parser/metadata.php#L744-L746)

Dokuwiki code:
```
 if (preg_match('/.(jpe?g|gif|png|webp|svg)$/i', $src)) { 
     $this->firstimage = $src; 
 } 
```

My edited code:
```
 if (preg_match('/.(jpe?g|gif|png|webp|svg|jxl|avif)$/i', $src)) {
     $this->firstimage = $src; 
 } 
```

Whether they will change it to that or not I don't know.
So yes it works and this issue is closed. Thank you for your help!

You can see the issue I filed here: [ firstimage does not return correct values for images other than PNGs, JPEGs or GIFs #4269 ](https://github.com/dokuwiki/dokuwiki/issues/4269).
