### ISSUE TITLE
Namespaces end up in the Tree 

### ISSUE THREAD

**Issue by NickStavros** [gturri/nspages#116] opened 2021-05-01 00:19 UTC
When I use the following command:

`<nspages ai:private:taxonomy:01_content:trees -tree -r -subns -pagesInNs -h1 -textNs="List of AI Taxonomies">
`

I was expecting only to have the names of the pages in the tre s in the example. instead, if there are sub-namespaces, then the namespace is added to the tree and then the child page names. note the gray line of text with the namespace on it, See attached:

<img width="546" alt="Screen Shot 2021-04-30 at 5 16 46 PM" src="https://user-images.githubusercontent.com/10712878/116764970-e3cf2b80-a9d7-11eb-89a4-7cc93b6d8cf0.png">

I have looked at all the options and can't find an option to suppress it to get it to look like the example. Any help would be appreciated.

**Comment by gturri** [comment] 2021-05-01 09:29
Hi,

Thanks for this bug report.

> I was expecting only to have the names of the pages
The flag "-subns" means that subnamespaces should be displayed, so you
might want to consider removing it

>  if there are sub-namespaces, then the namespace is added to the tree
Yes, that's what the flag -pagesInNs does: it displays the namespaces along
with the pages

> note the gray line of text with the namespace on it
If I remember correctly it represents a node of the tree for which the
target of the link doesn't exist. Said différent I think this node is grey
because you don't have a
`ai:private:taxonomy:01_content:trees:aiapps:nlapps:start` page

Does that give you enough clue to get the rendering you're looking for?

**Comment by gturri** [comment] 2021-08-15 16:51
(closing because an answer has been given more than 3 months ago and, though the bug reporter didn't confirmed that it solved his issue, he didn't gave information which leads to believe that he still experience an issue either)

**Closed by gturri** 2021-08-15 16:51 UTC

**Comment by Kirin92** [comment] 2021-12-04 19:22
Hey~ I know this issue is older but I got the same problem and I still don't know how to fix it. 
The path kirinspace/item do exist and it's on the bottom for some reason and the grey namespace on top. What should I do?
![chrome_Lf8kkwQvul](https://user-images.githubusercontent.com/52088060/144722035-efa232f8-13e0-4104-b952-e62eb709ae2b.png)

**Comment by gturri** [comment] 2021-12-05 23:04
hi @Kirin92 ,
Please post the `<nspages>` line you are using (it would help if I know which flags you use here)

**Comment by Kirin92** [comment] 2021-12-06 08:19
Yeah sure~
`<nspages .:kirinspace -tree -subns -pagesInNs -r -h1 -textNs="Meine Seiten">`
This is the code. I ended up deleting the "kirinspace:item" page and now it's somewhat correct but of course it's not what I was expecting
![chrome_wDPEbeGjKv](https://user-images.githubusercontent.com/52088060/144811294-687b0dc1-4bba-4da9-bba8-a8117cb8892b.png)
On the other hand if I click the link to the non existing page it's called "kirinspace/item/start". If I fill it everything seems to work but I don't want this path
![chrome_Sr8jpOXTwG](https://user-images.githubusercontent.com/52088060/144811571-02515155-5267-4dfa-9530-8d6b28b9a491.png)
.

**Comment by gturri** [comment] 2021-12-06 10:54
that's weird. I'm not able to reproduce this behavior. Did you use both `-subns` and `-pagesInNs` in your first screenshot? I would have expected the first bullet of the list (`kirinspace:item:`) to be a link then.

**Comment by Kirin92** [comment] 2021-12-06 11:02
I never changed that code. So yes I did use both. 
Maybe I use an other plugin which make this strange behavior occur? But I can't think of one...

That's how it looks like in the sitemap
![chrome_kZHdhnSli2](https://user-images.githubusercontent.com/52088060/144834847-bd34223c-16c8-4fc9-9fba-153edba26af7.png)
I just don't know why "item" is seperate? 
(pls ignore "laender")

**Comment by gturri** [comment] 2021-12-06 13:15
I'm not sure I understand the issue. Could you please open to me an access to your wiki (at least a read access to a test wiki which reproduces the issue) so I can see it directly? If that's ok with you, you could send me the credentials by mail at guillaume <dot> turri <a> gmail <dot> com

**Comment by Kirin92** [comment] 2021-12-06 13:30
sure but I think you can test it in my current wiki. I'll send you the mail.

**Comment by gturri** [comment] 2021-12-06 22:48
Thanks.
So, I went to your wiki, re-created the page `kirinspace:item` and I indeed observe the behavior you were describing.
The good news is that I am now able to reproduce the issue on my side (so feel free to change the credentials you sent me: I won't need them anymore).
The bad news is that I'm not sure I understand everything about this display.

More precisely: in your screenshot it is expected that `kirinspace/item` is displayed at the bottom: it is considered as the page `item` whereas the `kirinspace:item:` displayed at the top represent the namespace `item:` (and it should point at either `kirinspace:item:start` or `kirinspace:item:item` if one of those pages exist)

To put it in a nutshell:

- I don't understand why the first item on your list appears in grey rather than as a link to the unexisting `kirinspace:item:start` page and I'll try to take some time to investigate this (but I must admit I'm a bit busy lately and I'm not to sure when I'll have time to actually deep dive on this)
- But perhaps you could fix your issue by creating the page `kirinspace:item:start` instead of `kirinspace:item`

**Comment by Kirin92** [comment] 2021-12-07 07:23
Alright :D 
Take your time you need. Thank you ~

**Comment by gturri** [comment] 2021-12-11 07:36
FTR: I've created #120 to track this issue
