### ISSUE TITLE
hide page list if no pages present

### ISSUE THREAD

**Issue by rattkin** [gturri/nspages#35] opened 2015-06-11 14:05 UTC
Please add option to hide the "no pages in this namespace" message
specifically, nopages & nosubns

I can try to do the work, and subnit a pull request. Please advise on what the parameters should be. I suggest:
-hidenopages and -hidenosubns

**Comment by gturri** [comment] 2015-06-11 17:02
It seems to be interesting feature.

Yes, feel free to submit a pull request. If you can also add a non
regression test, it would be awesome!

The name of the options you suggest seems good.

Do not hesitate to ask if you have any
questions regarding implementation.

**Comment by rattkin** [comment] 2015-06-16 08:02
I have a pull request almost ready.

No regression test, sorry.
All my linux servers have just command line, no firefox. Also, maven is not
available for opensuse as a package, so there would be an extensive setup
required. (java ugh). Looks interesting though.

Thank You.
Regards,
Jan
​

**Comment by gturri** [comment] 2015-06-16 08:36
Yes, I know the test framework I put in place is a bit "exotic". No problem, I'll handle this part myself.

**Comment by gturri** [comment] 2015-06-16 17:46
Fixed by #36

**Closed by gturri** 2015-06-16 17:46 UTC
