### ISSUE TITLE
Warnings: optionParser.php and printer.php

### ISSUE THREAD

**Issue by nerun** [gturri/nspages#137] opened 2022-11-24 19:27 UTC
I am receiving this warning:
```
PHP Warning:  Undefined array key 0 in .../wiki/lib/plugins/nspages/optionParser.php on line 139
PHP Warning:  Trying to access array offset on value of type null in .../wiki/lib/plugins/nspages/printers/printer.php on line 115
```
This is the page in my wiki generating these issues: [RPG Livre - Wiki: Projetos](https://www.gurpzine.com.br/wiki/doku.php?id=wiki:projetos:start).

Here my settings:
![settings](https://user-images.githubusercontent.com/3987342/203853678-366bff60-599d-4e14-a3a8-589b69c46c4d.png)

Here the code i am using:
```
<nspages -tree -r -h1 -textNs="" -textPages="" -exclude>
```
My PHP version is 8.1.

**Comment by gturri** [comment] 2022-11-24 20:24
thanks for this bug report.
Could you please let me know which version of the plugin you are using? (you should see it at https://www.gurpzine.com.br/wiki/doku.php?do=admin&page=extension ; click on the arrow which points at the bottom to reveal the version)
![image](https://user-images.githubusercontent.com/308601/203859087-e50af12f-e732-4da7-9095-fa3d698ed0d7.png)

**Comment by nerun** [comment] 2022-11-24 20:51
2022-11-24

**Comment by gturri** [comment] 2022-11-24 20:57
Thanks.

I think the issue is that PHP8 is stricter than PHP7 and that I'm currently only testing against PHP7...

I think I understand where the first warning you mention comes from. I hope I should be able to fix it in a couple of days. I'll look into the other one afterwards.
Meanwhile, if you stumble on other similar warning, please report them as well.

**Comment by nerun** [comment] 2022-11-27 16:27
@gturri found a fix one error:

# FIX for /nspages/printers/printer.php on line 115
Find this at line 115
```php
if($item['type'] !== 'd') {
```
Change to this:
```php
if(isset($item) && $item['type'] !== 'd') {
```

**Comment by nerun** [comment] 2022-11-27 18:29
# FIX for _optionParser.php_ on line 139
Find at line 139:
```php
$match = optionParser::_removeFromMatch($found[0], $match);
```
Change to:
```php
if(sizeof($found) > 0) {
    $match = optionParser::_removeFromMatch($found[0], $match);
}
```

**Comment by nerun** [comment] 2022-11-27 18:32
It's solved for me, you can close it whenever you want.

**Comment by gturri** [comment] 2022-11-27 21:11
Thanks for this heads up!

It turns out that, thanks to your bug report, I noticed other PHP warnings. They are fixed with https://github.com/gturri/nspages/commit/5b8488d9bea5c6cca934c2b1a8b6423cace329a4 . I encourage you to update nspages in order to benefit from all those fixes.

**Closed by gturri** 2022-11-27 21:11 UTC
