### ISSUE TITLE
list pages for ThisNS in a generic format

### ISSUE THREAD

**Issue by GitWonder** [gturri/nspages#128] opened 2022-08-19 17:29 UTC
Is there a way to compile a list of pages for this namespace in a generic way, i.e. 
<nspages .:> or <nspages @currentNS>
 rather than explicitly name the namespace? This would enable me to more freely move and rename pages and namespaces and also template the format.

**Comment by gturri** [comment] 2022-08-19 19:32
If I understand correctly what you say, I think that just `<nspages>` should be what you are looking for.
Does that answer you qyestion? If it does not, please let me know what I misunderstood.

**Comment by GitWonder** [comment] 2022-08-19 23:57
I am building a wiki for handover to a client. All the plugins I am using need to be as generic in their execution as possible. <nspages> does a lot of what is needed but I can't see a generic method of displaying pages/namespaces within namespaces

If I have docs namespace containing process namespace containing process 1 page and hr processes namespace
`[docs]
docs.txt
  - [processes]
  - process.txt
    [hr_processes]
    - hr_processes.txt
    - process_1.txt`

What I need is if I were to place the code in the top level docs it would correctly show the index of everything from root down, but if I were to paste the same code to [hr_processes] it would show the index for everything in hr_processes only.

All the other plug-ins I've looked at require the namespace to be specifically declared which is causing me a lot of pain while structure is being finalised - movePage doesn't properly interact and the second issue is that I can't just place the code in a template and let the user create their page within a scaffold of genericised statements.

**Comment by gturri** [comment] 2022-08-20 19:05
I'm afraid I'm not sure I get what you try to achieve.

When you say
> What I need is if I were to place the code in the top level docs it would correctly show the index of everything from root down, but if I were to paste the same code to [hr_processes] it would show the index for everything in hr_processes only

do you mean that you would like to have a syntax which would display all the pages from the root of the wiki regardless of the page where the syntax is used? In that case, would `<nspages :>`  fit your need? This would always consider the root of your wiki, regardless of the page were you put it.

Alternatively, if you're interested in having a sitemap regarless of the location, you might want to consider putting it in a sidebar (that would appear on every page of the wiki). I haven't done in a while and I don't exactly remember how it work, but you might find more clue about it on https://www.dokuwiki.org/faq:sidebar#how_can_i_have_an_automatic_navigation_in_my_sidebar

Does any of this answer your question?
If it does not, please give me an example more precise on what you're trying to achieve (in particular stating clearly which page should display exactly what)

**Comment by gturri** [comment] 2022-08-20 19:11
If I understand correctly your example, just putting `<nspages>` on your page should do what you want:
- if you put `<nspages>` on a top levels docs it would show the index of everything in the root
- if you put the same code (i.e.: still `<nspages>`, without option) on `hr_processes` it would show pages in in the `hr_processes` namespace only (because when no namespace is provided, this plugin consider we're interested in the current one)

Does that fit your needs?

**Comment by GitWonder** [comment] 2022-08-20 23:40
Yes that is exactly what I am looking for.

I think there is something wrong with my Dokuwiki setup then because if I place <nspages> at the top of my hierarchy and use the same <nspages> in hr_processes.txt it does not show just the pages in [hr_processes], it shows the entire hierarchy

**Comment by gturri** [comment] 2022-08-21 11:51
I'm not sure I understand the behavior you describe. Could you reproduce the issue on a public instance of dokuwiki and send me the url so I could see it for myself?

**Comment by gturri** [comment] 2022-08-21 19:24
I'm noticing that I missed your edition, and it's possible that this is the explanation of this behavior. My understanding is that:


* Dokuwiki considers that there are 2 possible options for the location of the main page of a namespace. Namely, the main page of the namespace `:hr_processes` may be either:
  * `:hr_processes:start`
  * or `:hr_processes`

* However nspages does not implement the exact same logic: it considers that:
  * `:hr_processes:start` is part of the namespace `:hr_processes:`
  * but that `:hr_processes` is not part of it (it considers that it is part of the parent namespace)

I'm not too sure if that's a bug in nspages or if it's a bug in a Dokuwiki API used by ns pages (and I'm not sure I'll have time to figure it out any time soon, so I guess I'll leave this bug report open for now). Anyway, it seems that in your wiki you have `:hr_processes`, and a solution would be to move this page to `:hr_processes:start` instead.

**Comment by gturri** [comment] 2024-10-06 20:01
This should be fixed by the last version, as you can now use `<nspages ~>` on your page and it should lead to the required behavior (ie: considering that the current page represents the sub-namespace you're interested in)

**Closed by gturri** 2024-10-06 20:01 UTC
Labels: bug report
